version: '3.8'

services:
  postgres:
    image: postgres:16-alpine # Используем легкий образ Postgres 16
    container_name: java-postgres-db
    environment:
      POSTGRES_DB: myappdb        # Имя создаваемой БД
      POSTGRES_USER: sa        # Логин
      POSTGRES_PASSWORD: pass # Пароль
    ports:
      - "5432:5432" # Пробрасываем порт наружу (чтобы можно было подключиться DBeaver/pgAdmin)
    volumes:
      - postgres-data:/var/lib/postgresql/data # Сохраняем данные при перезапуске контейнера
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sa -d myappdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rest-api-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-rest-api
    ports:
      - "8080:8080"  # Пробрасываем порт 8080 из контейнера на хост
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myappdb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy # Ждем, пока БД станет готова к приемке соединений
    restart: on-failure # Если приложение упало при старте (БД еще не готова), перезапустить

volumes:
  postgres-data: